#pragma once
#include <assert.h>
#include "glm/glm.hpp"
#include <glad/glad.h>
#include <string>
// Wraps an OpenGL program: compiles vertex/fragment shaders, links, and exposes uniform setters.
// Templated SendUniform has explicit specializations for common types used in this project.
class ShaderProgram
{
public:
	ShaderProgram(std::string vertexShaderPath, std::string fragmentShaderPath);//Compiles and links the shaders.
	ShaderProgram(const ShaderProgram& other) = delete;
	ShaderProgram& operator=(const ShaderProgram& other) = delete;
	~ShaderProgram() noexcept;
	unsigned int GetID() const;	//Returns the shader program ID generated by OpenGL.
public:
	//Define the uniform sending functions using some elegant templating.
	template<typename T>
	void SendUniform(std::string uniformName, const T& value)
	{
		assert(false); //Trying to send an unsupported type.
	}
	// Specializations are defined out-of-class below for GCC/Clang compatibility.
private:
	unsigned int GetUniformID(std::string uniformName) const;	//Returns the identifier of the given uniform.
private:
	unsigned int shaderProgramID;
	};

// Define template specializations out-of-class to satisfy GCC
template<>
inline void ShaderProgram::SendUniform<glm::mat4>(std::string uniformName, const glm::mat4& value)
{
	glUniformMatrix4fv(GetUniformID(uniformName), 1, GL_FALSE, &value[0][0]);
}

template<>
inline void ShaderProgram::SendUniform<glm::mat3>(std::string uniformName, const glm::mat3& value)
{
	glUniformMatrix3fv(GetUniformID(uniformName), 1, GL_FALSE, &value[0][0]);
}

template<>
inline void ShaderProgram::SendUniform<glm::vec3>(std::string uniformName, const glm::vec3& value)
{
	glUniform3fv(GetUniformID(uniformName), 1, &value[0]);
}

template<>
inline void ShaderProgram::SendUniform<glm::vec4>(std::string uniformName, const glm::vec4& value)
{
	glUniform4fv(GetUniformID(uniformName), 1, &value[0]);
}

template<>
inline void ShaderProgram::SendUniform<int>(std::string uniformName, const int& value)
{
	glUniform1i(GetUniformID(uniformName), value);
}

template<>
inline void ShaderProgram::SendUniform<float>(std::string uniformName, const float& value)
{
	glUniform1f(GetUniformID(uniformName), value);
}